
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pentao
 */
public class adminAddData extends javax.swing.JFrame {
    
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;

    /**
     * Creates new form adminAddData
     */
    public adminAddData() {
        initComponents();
        conn=connection.ConnecrDb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        notice = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        recfield = new javax.swing.JTextField();
        a_eptot = new javax.swing.JLabel();
        comfield = new javax.swing.JTextField();
        totfield = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        ad_name = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        finfield = new javax.swing.JTextField();
        a_epfin = new javax.swing.JLabel();
        seasonfield = new javax.swing.JTextField();
        a_watchtype = new javax.swing.JLabel();
        d_comments = new javax.swing.JLabel();
        d_reception = new javax.swing.JLabel();
        viewfield = new javax.swing.JTextField();
        genrefield = new javax.swing.JTextField();
        d_genre = new javax.swing.JLabel();
        a_season = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        basicButton = new javax.swing.JButton();
        specButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SOArchiver: Add Data");

        notice.setText("All forms are required to be filled.");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 102, 0)), "Anime Database Addition Form", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 1, 14), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel1.setToolTipText("All Preset Text is simply an example.");

        recfield.setText("Unknown");

        a_eptot.setText("Total Episodes");
        a_eptot.setToolTipText("Enter the Anime's total NUMBER of episodes.");

        comfield.setText("Story by Pentao, Illustrations by Anonamos");

        totfield.setText("25");

        addButton.setText("Add to Database");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        ad_name.setText("Anime Name");
        ad_name.setToolTipText("The name of the Anime. WARNING: Do not enter an Anime name that's already in the database!");

        namefield.setText("Harmonic Dissonance");

        finfield.setText("25");

        a_epfin.setText("Episodes Finished");
        a_epfin.setToolTipText("Enter the NUMBER of episodes finished within club. Ensure that it is a number input.");

        seasonfield.setText("Summer 2015");

        a_watchtype.setText("View Type");
        a_watchtype.setToolTipText("As in Line Up, Marathon, Random Viewing, Wildcard, etc.");

        d_comments.setText("Comments");
        d_comments.setToolTipText("Add in any other personal comments about the anime you feel is helpful. You can't leave this blank.");

        d_reception.setText("Reception");
        d_reception.setToolTipText("Enter how the club seemed to feel about the Anime.");

        viewfield.setText("Line Up");

        genrefield.setText("Comedy, Drama, Slice of Life");

        d_genre.setText("Genre(s)");
        d_genre.setToolTipText("Enter the various genres the Anime may fall under.");

        a_season.setText("Season Watched");
        a_season.setToolTipText("Enter the Season the series was watched. Typically this is denoted by \"Season Year\", for example: Fall 2012. You do not need to enter quotes.");

        clear.setText("Clear");
        clear.setToolTipText("Clears all fields so you don't have to delete them all individually.");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(a_epfin, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(a_watchtype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ad_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(a_eptot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(a_season, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(d_genre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(d_reception, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(d_comments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namefield)
                    .addComponent(viewfield)
                    .addComponent(finfield)
                    .addComponent(totfield)
                    .addComponent(seasonfield)
                    .addComponent(genrefield)
                    .addComponent(recfield)
                    .addComponent(comfield)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ad_name)
                    .addComponent(namefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a_watchtype)
                    .addComponent(viewfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a_epfin)
                    .addComponent(finfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a_eptot)
                    .addComponent(totfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a_season)
                    .addComponent(seasonfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(d_genre)
                    .addComponent(genrefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(d_reception)
                    .addComponent(recfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(d_comments)
                    .addComponent(comfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(clear))
                .addContainerGap())
        );

        backButton.setText("Home");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        basicButton.setText("Basic");
        basicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basicButtonActionPerformed(evt);
            }
        });

        specButton.setText("Specific");
        specButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(notice, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(basicButton)
                        .addGap(17, 17, 17)
                        .addComponent(specButton)
                        .addGap(18, 18, 18)
                        .addComponent(backButton))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notice)
                    .addComponent(backButton)
                    .addComponent(basicButton)
                    .addComponent(specButton))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        String genre = genrefield.getText();
        String reception = recfield.getText();
        String comments = comfield.getText();
        String name = namefield.getText();
        if (namefield.getText().trim().length() == 0 || finfield.getText().length() == 0 || totfield.getText().length() == 0 || seasonfield.getText().length() == 0 || viewfield.getText().length() == 0 || comfield.getText().length() == 0 || genrefield.getText().length() == 0 || finfield.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Please fill out the fields.");
        } else { 
            try {
                String sql = "INSERT INTO Anime (a_name, a_epfin, a_eptotal, a_season, a_watchtype) VALUES (?,?,?,?,?)";

                pst = conn.prepareStatement(sql);
                pst.setString(1, namefield.getText());
                pst.setString(2, finfield.getText());
                pst.setString(3, totfield.getText());
                pst.setString(4, seasonfield.getText());
                pst.setString(5, viewfield.getText());
            
              pst.execute();
            
             JOptionPane.showMessageDialog(null, "Anime successfully added.");
         }
         catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            }
            
            try {
                String sql = "UPDATE Data SET d_genre='"+genre+"' ,d_reception ='"+reception+"' ,d_comments ='"+comments+"' WHERE d_name ='"+name+"'";
                pst = conn.prepareStatement(sql);
                pst.execute();
            }
            catch(Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_addButtonActionPerformed

    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        close();
        adminHome p = new adminHome();
        p.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void basicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basicButtonActionPerformed
        close();
        adminBasicData p = new adminBasicData();
        p.setVisible(true);
    }//GEN-LAST:event_basicButtonActionPerformed

    private void specButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specButtonActionPerformed
        close();
        adminSpecificData p = new adminSpecificData();
        p.setVisible(true);
    }//GEN-LAST:event_specButtonActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        finfield.setText("");
        genrefield.setText("");
        namefield.setText("");
        recfield.setText("");
        comfield.setText("");
        totfield.setText("");
        viewfield.setText("");
        seasonfield.setText("");
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminAddData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminAddData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminAddData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminAddData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminAddData().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a_epfin;
    private javax.swing.JLabel a_eptot;
    private javax.swing.JLabel a_season;
    private javax.swing.JLabel a_watchtype;
    private javax.swing.JLabel ad_name;
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton basicButton;
    private javax.swing.JButton clear;
    private javax.swing.JTextField comfield;
    private javax.swing.JLabel d_comments;
    private javax.swing.JLabel d_genre;
    private javax.swing.JLabel d_reception;
    private javax.swing.JTextField finfield;
    private javax.swing.JTextField genrefield;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField namefield;
    private javax.swing.JLabel notice;
    private javax.swing.JTextField recfield;
    private javax.swing.JTextField seasonfield;
    private javax.swing.JButton specButton;
    private javax.swing.JTextField totfield;
    private javax.swing.JTextField viewfield;
    // End of variables declaration//GEN-END:variables
}
